package com.brilliantinfotech.dao.impl;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Persistent UNIQUE KEY entity with DynamoDB
 * 
 * @author Rahul Landge
 */

@DynamoDBTable(tableName = "UNIQUE_KEY")
public class UniqueKey implements Serializable {

	private static final long serialVersionUID = 1L;

	@DynamoDBHashKey(attributeName = "ID")
	@DynamoDBAutoGeneratedKey
	protected String id;

	@DynamoDBAttribute(attributeName = "URL_SHORTENER_UNIQUE_KEY")
	protected String key;
	
	@DynamoDBAttribute(attributeName = "READ_ONLY")
	protected String readOnlyFlag;
	

	public String getReadOnlyFlag() {
		return readOnlyFlag;
	}

	public void setReadOnlyFlag(String readOnlyFlag) {
		this.readOnlyFlag = readOnlyFlag;
	}

	/**
	 * Default constructor for JPA only.
	 */
	public UniqueKey() {

	}

	public UniqueKey(String id, String key) {
		this.id = id;
		this.key = key;
	}

	public String getId() {
		return id;
	}

	protected void setId(String id) {
		this.id = id;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

}
